TravelTimeError: add retrieveCause() with optional return type
This exposes the causes that e.g. IOError detects.
This can be useful for users to show more detailed errors in their
applications.

IOError and XmlError support returning the cause.
Other subclasses return Option.none().

Added ErrorTest to check whether Error classes are properly implemented.
Checking wrong credentials (ResponseError) and explicitly setting up
IOError and XmlError objects to check the retrieved exceptions.

Extended documentation for how to set up testing.